export type BlogPost = {
  slug: string;
  title: string;
  url: string;
  image?: string;
  /** When set, the card's title/description are read from messages.blog.posts.<translationKey> instead of the static `title` above. */
  translationKey?: string;
};

export const blogPosts: BlogPost[] = [
  {
    slug: "stopkove-rasple-saburrtooth-usa-sprievodca",
    title: "Stopkové rašple Saburrtooth USA – sprievodca tvarmi a drsnosťami",
    url: "https://eshop.marosko.sk/n/stopkove-rasple-saburrtooth-usa-sprievodca",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/nastroje-do-priamej-brusky/featured-shank.jpg",
    translationKey: "saburrtoothRasple",
  },
  {
    slug: "manpa-tvarovacie-rasplicky-na-oci-sada-8ks",
    title: "Manpa tvarovacie rašpličky na oči – sada 8 ks",
    url: "https://eshop.marosko.sk/n/manpa-tvarovacie-rasplicky-na-oci-sada-8ks",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/manpa/vypalovacie-frezky/sova-oci-s-vypalovakmi-manpa.jpg",
    translationKey: "manpaOci",
  },
  {
    slug: "manpa-brusny-vejar-65mm-ez-sander-stopka",
    title: "Manpa EZ Sander 65 mm – brúsny vejár",
    url: "https://eshop.marosko.sk/n/manpa-brusny-vejar-65mm-ez-sander-stopka",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/manpa/brusny-vejar-65/insert-special-orig.jpg",
    translationKey: "manpaEzSander",
  },
  {
    slug: "dlata-pre-zaciatocnika",
    title: "Výber dlát pre začiatočníkov (M-stein)",
    url: "https://eshop.marosko.sk/n/dlata-pre-zaciatocnika",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/dlata-m-stein-/img-20210506-104954-01.jpeg",
    translationKey: "dlataZaciatocnik",
  },
  {
    slug: "sada-dlat-pre-zaciatocnikov-4-dielna-drevo-rezba-stubai",
    title: "Stubai – sada dlát pre začiatočníkov, 4-dielna",
    url: "https://eshop.marosko.sk/n/sada-dlat-pre-zaciatocnikov-4-dielna-drevo-rezba-stubai",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/rucne-naradie/stubai/s520001-stubai-/4-diela-sada-stubai.webp",
    translationKey: "stubaiSada",
  },
  {
    slug: "arbortech-mini-grinder-mg1000-akumulatorovy-frezovaci-a-rezbarsky-set-rezbarska-sada",
    title: "Arbortech Mini Grinder MG1000 – akumulátorový set",
    url: "https://eshop.marosko.sk/n/arbortech-mini-grinder-mg1000-akumulatorovy-frezovaci-a-rezbarsky-set-rezbarska-sada",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/na-drevo/arbortech/aku-mini-grinder-/mg-1000-aku-mini-grinder-.jpg",
    translationKey: "arbortechMiniGrinder",
  },
  {
    slug: "lesticka-180-mm-1200-w-silverline1",
    title: "Leštička 180 mm, 1200 W, Silverline",
    url: "https://eshop.marosko.sk/n/lesticka-180-mm-1200-w-silverline1",
    image: "https://eshop.marosko.sk/resize/e/1200/630/files/elektricke-naradie/silverline/lesticka-1200w-180mm/264569-enwnmpro13.jpg",
    translationKey: "silverlineLesticka",
  },
  {
    slug: "arbortech-power-chisel-elektricke-dlato-7-dielna-sada",
    title: "Arbortech Power Chisel – elektrické dláto, 7-dielna sada",
    url: "https://eshop.marosko.sk/n/arbortech-power-chisel-elektricke-dlato-7-dielna-sada",
    image: "https://eshop.marosko.sk/resize/e/1200/630/files/elektricke-naradie/nahradne-dlata-arbortech/arbortech-power-chisel.jpg",
    translationKey: "arbortechPowerChisel",
  },
  { slug: "arbortech-contour-random-sander", title: "Arbortech Contour Random Sander", url: "https://eshop.marosko.sk/n/arbortech-contour-random-sander" },
  { slug: "arbortech-turbo-scraper", title: "Arbortech Turbo Scraper", url: "https://eshop.marosko.sk/n/arbortech-turbo-scraper" },
  { slug: "arbortech-spheroplane", title: "Arbortech SpheroPlane", url: "https://eshop.marosko.sk/n/arbortech-spheroplane" },
  { slug: "arbortech-turbo-plane", title: "Arbortech Turbo Plane", url: "https://eshop.marosko.sk/n/arbortech-turbo-plane" },
  { slug: "manpa-novinky-frezky-trojuholnikove", title: "Manpa novinky – trojuholníkové frézky", url: "https://eshop.marosko.sk/n/manpa-novinky-frezky-trojuholnikove" },
  {
    slug: "frezovaci-kotuc-do-uhlovej-brusky-arbortech-woodcarver-profi-industrial",
    title: "Frézovací kotúč Arbortech Woodcarver PROFI-INDUSTRIAL",
    url: "https://eshop.marosko.sk/n/frezovaci-kotuc-do-uhlovej-brusky-arbortech-woodcarver-profi-industrial",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/na-drevo/arbortech/industrial/industrial-woodcarver-arbortech.jpg",
    translationKey: "arbortechWoodcarverProfi",
  },
  { slug: "hriadel-do-lesticky-urceny-pre-kotuc", title: "Hriadeľ do leštičky určený pre kotúč", url: "https://eshop.marosko.sk/n/hriadel-do-lesticky-urceny-pre-kotuc" },
  { slug: "brusny-system", title: "Brúsny systém", url: "https://eshop.marosko.sk/n/brusny-system" },
  { slug: "dlata-pre-zaciatocnikov-rucne", title: "Dláta pre začiatočníkov – ručné", url: "https://eshop.marosko.sk/n/dlata-pre-zaciatocnikov-rucne" },
  { slug: "hlbiace-zvonkove-frezy", title: "Hĺbiace zvonkové frézy", url: "https://eshop.marosko.sk/n/hlbiace-zvonkove-frezy" },
  { slug: "smirglovaci-nastavec-contor-sander-sada", title: "Šmirgľovací nadstavec Contour Sander, sada", url: "https://eshop.marosko.sk/n/smirglovaci-nastavec-contor-sander-sada" },
  { slug: "brusny-papier-vyseky-na-mieru", title: "Brúsny papier – výseky na mieru", url: "https://eshop.marosko.sk/n/brusny-papier-vyseky-na-mieru" },
  { slug: "saburrtooth-extreme-frezy", title: "Saburrtooth Extreme frézy", url: "https://eshop.marosko.sk/n/saburrtooth-extreme-frezy" },
  { slug: "arbortech-power-carving-unit", title: "Arbortech Power Carving Unit", url: "https://eshop.marosko.sk/n/arbortech-power-carving-unit" },
  { slug: "drazkovacia-frezovacia-stopka-pr20mm", title: "Drážkovacia frézovacia stopka, priemer 20 mm", url: "https://eshop.marosko.sk/n/drazkovacia-frezovacia-stopka-pr20mm" },
  { slug: "kotucova-sekana-raspla-pre-arbortech-okruhla-mini-grinder-a-merlin-50-mm", title: "Kotúčová sekaná rašpľa pre Arbortech Mini Grinder a Merlin, 50 mm", url: "https://eshop.marosko.sk/n/kotucova-sekana-raspla-pre-arbortech-okruhla-mini-grinder-a-merlin-50-mm" },
  { slug: "brusny-kotuc-s-tvrdo-kovom-s-hranou-pr125mm-jemny", title: "Brúsny kotúč s tvrdokovom, s hranou, priemer 125 mm, jemný", url: "https://eshop.marosko.sk/n/brusny-kotuc-s-tvrdo-kovom-s-hranou-pr125mm-jemny" },
  { slug: "brusny-hribik-na-dokoncovacie-prace", title: "Brúsny hríbik na dokončovacie práce", url: "https://eshop.marosko.sk/n/brusny-hribik-na-dokoncovacie-prace" },
  { slug: "triton-upinacia-svorka-sja100e", title: "Triton upínacia svorka SJA100E", url: "https://eshop.marosko.sk/n/triton-upinacia-svorka-sja100e" },
  { slug: "brusna-hviezda-z-platnovych-vysekov", title: "Brúsna hviezda z plátnových výsekov", url: "https://eshop.marosko.sk/n/brusna-hviezda-z-platnovych-vysekov" },
  { slug: "predlzovacie-rameno-s-viacucelovym-nadstavcom", title: "Predlžovacie rameno s viacúčelovým nadstavcom", url: "https://eshop.marosko.sk/n/predlzovacie-rameno-s-viacucelovym-nadstavcom" },
  { slug: "sikmy-brusny-kotuc-s-tvrdo-kovom-pr115mm", title: "Šikmý brúsny kotúč s tvrdokovom, priemer 115 mm", url: "https://eshop.marosko.sk/n/sikmy-brusny-kotuc-s-tvrdo-kovom-pr115mm" },
  {
    slug: "novinka-od-spolocnosti-arbortech",
    title: "Arbortech Mini Carver 1000W – elektrická frézka",
    url: "https://eshop.marosko.sk/n/novinka-od-spolocnosti-arbortech",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/elektricke-naradie/arbortech-novinka/mini-carver/mini-carver-nova-1000w.png",
    translationKey: "arbortechMiniCarver",
  },
  { slug: "rustikalny-efekt-dreva", title: "Rustikálny efekt dreva", url: "https://eshop.marosko.sk/n/rustikalny-efekt-dreva" },
  { slug: "priama-bruska-500w", title: "Priama brúska 500 W", url: "https://eshop.marosko.sk/n/priama-bruska-500w" },
  {
    slug: "suchy-zips-na-mieru",
    title: "Suchý zips – podklad pre šmirgle na mieru",
    url: "https://eshop.marosko.sk/n/suchy-zips-na-mieru",
    image: "https://eshop.marosko.sk/resize/k/465/310/files/brusne-vyseky/samolepiace-podlozky/-vyr-podlozka-suchy-zip.jpg",
    translationKey: "suchyZips",
  },
  { slug: "predlzenie-hriadela-na-uhlovej-bruske-m-14-m-14", title: "Predĺženie hriadeľa na uhlovej brúske, M14 – M14", url: "https://eshop.marosko.sk/n/predlzenie-hriadela-na-uhlovej-bruske-m-14-m-14" },
  { slug: "redukcia-m146mm", title: "Redukcia M14 / 6 mm", url: "https://eshop.marosko.sk/n/redukcia-m146mm" },
  { slug: "turbo-plane", title: "Turbo Plane", url: "https://eshop.marosko.sk/n/turbo-plane" },
  { slug: "diamantovy-brusny-kotuc-drazkovy-drsnost-12639", title: "Diamantový brúsny kotúč drážkový, drsnosť 126/39", url: "https://eshop.marosko.sk/n/diamantovy-brusny-kotuc-drazkovy-drsnost-12639" },
  { slug: "rasplovy-kotuc-rucne-sekany-plochy-gulata-hrana-125-mm", title: "Rašpľový kotúč, ručne sekaný, plochý, guľatá hrana, 125 mm", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-rucne-sekany-plochy-gulata-hrana-125-mm" },
  { slug: "mini-raspla-sekana", title: "Mini rašpľa sekaná", url: "https://eshop.marosko.sk/n/mini-raspla-sekana" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-drsna", title: "Ihličková rašpľa šikmá, oblá, bez otvorov, priemer 100 mm, drsná", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-drsna" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-jemna-100-mm", title: "Ihličková rašpľa šikmá, oblá, bez otvorov, jemná, 100 mm", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-jemna-100-mm" },
  { slug: "ihlickova-raspla-plocha-rovna-o-100mm-extra-hruba", title: "Ihličková rašpľa plochá rovná, priemer 100 mm, extra hrubá", url: "https://eshop.marosko.sk/n/ihlickova-raspla-plocha-rovna-o-100mm-extra-hruba" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-extra-hruba", title: "Ihličková rašpľa šikmá, oblá, bez otvorov, priemer 100 mm, extra hrubá", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-extra-hruba" },
  { slug: "ihlickova-raspla-gulata-bez-otvorov-pr100mm-jemna", title: "Ihličková rašpľa guľatá, bez otvorov, priemer 100 mm, jemná", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvorov-pr100mm-jemna" },
  { slug: "raspla-zapustena-jemna-115mm-rovna-kzr-53", title: "Rašpľa zapustená, jemná, 115 mm, rovná, KZR 53", url: "https://eshop.marosko.sk/n/raspla-zapustena-jemna-115mm-rovna-kzr-53" },
  { slug: "raspla-valcova-120-20-x-222mm-kvo-122", title: "Rašpľa valcová 120 × 20 × 222 mm, KVO 122", url: "https://eshop.marosko.sk/n/raspla-valcova-120-20-x-222mm-kvo-122" },
  { slug: "rasplovy-pilovy-kotuc-125-zapusteny", title: "Rašpľový pílový kotúč 125 mm, zapustený", url: "https://eshop.marosko.sk/n/rasplovy-pilovy-kotuc-125-zapusteny" },
  { slug: "nahradny-vymenny-noz-ball-gouge", title: "Náhradný výmenný nôž Ball Gouge", url: "https://eshop.marosko.sk/n/nahradny-vymenny-noz-ball-gouge" },
  { slug: "dlata-jednotlive-a-sady-ploche-spicate-gulate-v-ponuke-na-drevo", title: "Dláta jednotlivé a sady – ploché, špicaté, guľaté – v ponuke na drevo", url: "https://eshop.marosko.sk/n/dlata-jednotlive-a-sady-ploche-spicate-gulate-v-ponuke-na-drevo" },
  { slug: "rucne-sekane-rasple", title: "Ručne sekané rašple", url: "https://eshop.marosko.sk/n/rucne-sekane-rasple" },
  { slug: "rasplovy-kotuc-sekany-oblym-okrajom-125-mm-oval", title: "Rašpľový kotúč sekaný, oblým okrajom, 125 mm, ovál", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-sekany-oblym-okrajom-125-mm-oval" },
  { slug: "rasplovy-kotuc-sekany-ostrim-okrajom-125-mm-vecko", title: "Rašpľový kotúč sekaný, ostrým okrajom, 125 mm, véčko", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-sekany-ostrim-okrajom-125-mm-vecko" },
  { slug: "frezovacia-stopka-turboshaft", title: "Frézovacia stopka Turboshaft", url: "https://eshop.marosko.sk/n/frezovacia-stopka-turboshaft" },
  { slug: "ihlickova-raspla-gulata-bez-otvorov-pr100mm-hruba", title: "Ihličková rašpľa guľatá, bez otvorov, priemer 100 mm, hrubá", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvorov-pr100mm-hruba" },
  { slug: "ihlickova-raspla-gulata-bez-otvoru-pr100mm-drsna", title: "Ihličková rašpľa guľatá, bez otvoru, priemer 100 mm, drsná", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvoru-pr100mm-drsna" },
];
