export type BlogPost = {
  slug: string;
  title: string;
  url: string;
};

export const blogPosts: BlogPost[] = [
  { slug: "stopkove-rasple-saburrtooth-usa-sprievodca", title: "Stopkove rasple Saburrtooth USA sprievodca", url: "https://eshop.marosko.sk/n/stopkove-rasple-saburrtooth-usa-sprievodca" },
  { slug: "manpa-tvarovacie-rasplicky-na-oci-sada-8ks", title: "Manpa tvarovacie rasplicky na oci sada 8 ks", url: "https://eshop.marosko.sk/n/manpa-tvarovacie-rasplicky-na-oci-sada-8ks" },
  { slug: "manpa-brusny-vejar-65mm-ez-sander-stopka", title: "Manpa brusny vejar 65 mm EZ sander stopka", url: "https://eshop.marosko.sk/n/manpa-brusny-vejar-65mm-ez-sander-stopka" },
  { slug: "dlata-pre-zaciatocnika", title: "Dlata pre zaciatocnika", url: "https://eshop.marosko.sk/n/dlata-pre-zaciatocnika" },
  { slug: "sada-dlat-pre-zaciatocnikov-4-dielna-drevo-rezba-stubai", title: "Sada dlat pre zaciatocnikov 4 dielna drevo rezba Stubai", url: "https://eshop.marosko.sk/n/sada-dlat-pre-zaciatocnikov-4-dielna-drevo-rezba-stubai" },
  { slug: "arbortech-mini-grinder-mg1000-akumulatorovy-frezovaci-a-rezbarsky-set-rezbarska-sada", title: "Arbortech mini grinder MG1000 akumulatorovy frezovaci a rezbarsky set rezbarska sada", url: "https://eshop.marosko.sk/n/arbortech-mini-grinder-mg1000-akumulatorovy-frezovaci-a-rezbarsky-set-rezbarska-sada" },
  { slug: "lesticka-180-mm-1200-w-silverline1", title: "Lesticka 180 mm 1200 w Silverline", url: "https://eshop.marosko.sk/n/lesticka-180-mm-1200-w-silverline1" },
  { slug: "arbortech-power-chisel-elektricke-dlato-7-dielna-sada", title: "Arbortech power chisel elektricke dlato 7 dielna sada", url: "https://eshop.marosko.sk/n/arbortech-power-chisel-elektricke-dlato-7-dielna-sada" },
  { slug: "arbortech-contour-random-sander", title: "Arbortech contour random sander", url: "https://eshop.marosko.sk/n/arbortech-contour-random-sander" },
  { slug: "arbortech-turbo-scraper", title: "Arbortech turbo scraper", url: "https://eshop.marosko.sk/n/arbortech-turbo-scraper" },
  { slug: "arbortech-spheroplane", title: "Arbortech spheroplane", url: "https://eshop.marosko.sk/n/arbortech-spheroplane" },
  { slug: "arbortech-turbo-plane", title: "Arbortech turbo plane", url: "https://eshop.marosko.sk/n/arbortech-turbo-plane" },
  { slug: "manpa-novinky-frezky-trojuholnikove", title: "Manpa novinky frezky trojuholnikove", url: "https://eshop.marosko.sk/n/manpa-novinky-frezky-trojuholnikove" },
  { slug: "frezovaci-kotuc-do-uhlovej-brusky-arbortech-woodcarver-profi-industrial", title: "Frezovaci kotuc do uhlovej brusky Arbortech woodcarver profi industrial", url: "https://eshop.marosko.sk/n/frezovaci-kotuc-do-uhlovej-brusky-arbortech-woodcarver-profi-industrial" },
  { slug: "hriadel-do-lesticky-urceny-pre-kotuc", title: "Hriadel do lesticky urceny pre kotuc", url: "https://eshop.marosko.sk/n/hriadel-do-lesticky-urceny-pre-kotuc" },
  { slug: "brusny-system", title: "Brusny system", url: "https://eshop.marosko.sk/n/brusny-system" },
  { slug: "dlata-pre-zaciatocnikov-rucne", title: "Dlata pre zaciatocnikov rucne", url: "https://eshop.marosko.sk/n/dlata-pre-zaciatocnikov-rucne" },
  { slug: "hlbiace-zvonkove-frezy", title: "Hlbiace zvonkove frezy", url: "https://eshop.marosko.sk/n/hlbiace-zvonkove-frezy" },
  { slug: "smirglovaci-nastavec-contor-sander-sada", title: "Smirglovaci nastavec contor sander sada", url: "https://eshop.marosko.sk/n/smirglovaci-nastavec-contor-sander-sada" },
  { slug: "brusny-papier-vyseky-na-mieru", title: "Brusny papier vyseky na mieru", url: "https://eshop.marosko.sk/n/brusny-papier-vyseky-na-mieru" },
  { slug: "saburrtooth-extreme-frezy", title: "Saburrtooth extreme frezy", url: "https://eshop.marosko.sk/n/saburrtooth-extreme-frezy" },
  { slug: "arbortech-power-carving-unit", title: "Arbortech power carving unit", url: "https://eshop.marosko.sk/n/arbortech-power-carving-unit" },
  { slug: "drazkovacia-frezovacia-stopka-pr20mm", title: "Drazkovacia frezovacia stopka pr. 20 mm", url: "https://eshop.marosko.sk/n/drazkovacia-frezovacia-stopka-pr20mm" },
  { slug: "kotucova-sekana-raspla-pre-arbortech-okruhla-mini-grinder-a-merlin-50-mm", title: "Kotucova sekana raspla pre Arbortech okruhla mini grinder a merlin 50 mm", url: "https://eshop.marosko.sk/n/kotucova-sekana-raspla-pre-arbortech-okruhla-mini-grinder-a-merlin-50-mm" },
  { slug: "brusny-kotuc-s-tvrdo-kovom-s-hranou-pr125mm-jemny", title: "Brusny kotuc s tvrdo kovom s hranou pr. 125 mm jemny", url: "https://eshop.marosko.sk/n/brusny-kotuc-s-tvrdo-kovom-s-hranou-pr125mm-jemny" },
  { slug: "brusny-hribik-na-dokoncovacie-prace", title: "Brusny hribik na dokoncovacie prace", url: "https://eshop.marosko.sk/n/brusny-hribik-na-dokoncovacie-prace" },
  { slug: "triton-upinacia-svorka-sja100e", title: "Triton upinacia svorka SJA100E", url: "https://eshop.marosko.sk/n/triton-upinacia-svorka-sja100e" },
  { slug: "brusna-hviezda-z-platnovych-vysekov", title: "Brusna hviezda z platnovych vysekov", url: "https://eshop.marosko.sk/n/brusna-hviezda-z-platnovych-vysekov" },
  { slug: "predlzovacie-rameno-s-viacucelovym-nadstavcom", title: "Predlzovacie rameno s viacucelovym nadstavcom", url: "https://eshop.marosko.sk/n/predlzovacie-rameno-s-viacucelovym-nadstavcom" },
  { slug: "sikmy-brusny-kotuc-s-tvrdo-kovom-pr115mm", title: "Sikmy brusny kotuc s tvrdo kovom pr. 115 mm", url: "https://eshop.marosko.sk/n/sikmy-brusny-kotuc-s-tvrdo-kovom-pr115mm" },
  { slug: "novinka-od-spolocnosti-arbortech", title: "Novinka od spolocnosti Arbortech", url: "https://eshop.marosko.sk/n/novinka-od-spolocnosti-arbortech" },
  { slug: "rustikalny-efekt-dreva", title: "Rustikalny efekt dreva", url: "https://eshop.marosko.sk/n/rustikalny-efekt-dreva" },
  { slug: "priama-bruska-500w", title: "Priama bruska 500 w", url: "https://eshop.marosko.sk/n/priama-bruska-500w" },
  { slug: "suchy-zips-na-mieru", title: "Suchy zips na mieru", url: "https://eshop.marosko.sk/n/suchy-zips-na-mieru" },
  { slug: "predlzenie-hriadela-na-uhlovej-bruske-m-14-m-14", title: "Predlzenie hriadela na uhlovej bruske m 14 m 14", url: "https://eshop.marosko.sk/n/predlzenie-hriadela-na-uhlovej-bruske-m-14-m-14" },
  { slug: "redukcia-m146mm", title: "Redukcia m146mm", url: "https://eshop.marosko.sk/n/redukcia-m146mm" },
  { slug: "turbo-plane", title: "Turbo plane", url: "https://eshop.marosko.sk/n/turbo-plane" },
  { slug: "diamantovy-brusny-kotuc-drazkovy-drsnost-12639", title: "Diamantovy brusny kotuc drazkovy drsnost 12639", url: "https://eshop.marosko.sk/n/diamantovy-brusny-kotuc-drazkovy-drsnost-12639" },
  { slug: "rasplovy-kotuc-rucne-sekany-plochy-gulata-hrana-125-mm", title: "Rasplovy kotuc rucne sekany plochy gulata hrana 125 mm", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-rucne-sekany-plochy-gulata-hrana-125-mm" },
  { slug: "mini-raspla-sekana", title: "Mini raspla sekana", url: "https://eshop.marosko.sk/n/mini-raspla-sekana" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-drsna", title: "Ihlickova raspla sikma obla bez otvorov o 100 mm drsna", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-drsna" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-jemna-100-mm", title: "Ihlickova raspla sikma obla bez otvorov jemna 100 mm", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-jemna-100-mm" },
  { slug: "ihlickova-raspla-plocha-rovna-o-100mm-extra-hruba", title: "Ihlickova raspla plocha rovna o 100 mm extra hruba", url: "https://eshop.marosko.sk/n/ihlickova-raspla-plocha-rovna-o-100mm-extra-hruba" },
  { slug: "ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-extra-hruba", title: "Ihlickova raspla sikma obla bez otvorov o 100 mm extra hruba", url: "https://eshop.marosko.sk/n/ihlickova-raspla-sikma-obla-bez-otvorov-o-100mm-extra-hruba" },
  { slug: "ihlickova-raspla-gulata-bez-otvorov-pr100mm-jemna", title: "Ihlickova raspla gulata bez otvorov pr. 100 mm jemna", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvorov-pr100mm-jemna" },
  { slug: "raspla-zapustena-jemna-115mm-rovna-kzr-53", title: "Raspla zapustena jemna 115 mm rovna KZR 53", url: "https://eshop.marosko.sk/n/raspla-zapustena-jemna-115mm-rovna-kzr-53" },
  { slug: "raspla-valcova-120-20-x-222mm-kvo-122", title: "Raspla valcova 120 20 x 222 mm KVO 122", url: "https://eshop.marosko.sk/n/raspla-valcova-120-20-x-222mm-kvo-122" },
  { slug: "rasplovy-pilovy-kotuc-125-zapusteny", title: "Rasplovy pilovy kotuc 125 zapusteny", url: "https://eshop.marosko.sk/n/rasplovy-pilovy-kotuc-125-zapusteny" },
  { slug: "nahradny-vymenny-noz-ball-gouge", title: "Nahradny vymenny noz ball gouge", url: "https://eshop.marosko.sk/n/nahradny-vymenny-noz-ball-gouge" },
  { slug: "dlata-jednotlive-a-sady-ploche-spicate-gulate-v-ponuke-na-drevo", title: "Dlata jednotlive a sady ploche spicate gulate v ponuke na drevo", url: "https://eshop.marosko.sk/n/dlata-jednotlive-a-sady-ploche-spicate-gulate-v-ponuke-na-drevo" },
  { slug: "rucne-sekane-rasple", title: "Rucne sekane rasple", url: "https://eshop.marosko.sk/n/rucne-sekane-rasple" },
  { slug: "rasplovy-kotuc-sekany-oblym-okrajom-125-mm-oval", title: "Rasplovy kotuc sekany oblym okrajom 125 mm oval", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-sekany-oblym-okrajom-125-mm-oval" },
  { slug: "rasplovy-kotuc-sekany-ostrim-okrajom-125-mm-vecko", title: "Rasplovy kotuc sekany ostrim okrajom 125 mm vecko", url: "https://eshop.marosko.sk/n/rasplovy-kotuc-sekany-ostrim-okrajom-125-mm-vecko" },
  { slug: "frezovacia-stopka-turboshaft", title: "Frezovacia stopka turboshaft", url: "https://eshop.marosko.sk/n/frezovacia-stopka-turboshaft" },
  { slug: "ihlickova-raspla-gulata-bez-otvorov-pr100mm-hruba", title: "Ihlickova raspla gulata bez otvorov pr. 100 mm hruba", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvorov-pr100mm-hruba" },
  { slug: "ihlickova-raspla-gulata-bez-otvoru-pr100mm-drsna", title: "Ihlickova raspla gulata bez otvoru pr. 100 mm drsna", url: "https://eshop.marosko.sk/n/ihlickova-raspla-gulata-bez-otvoru-pr100mm-drsna" },
];
