export type Brand = {
  id: number;
  slug: string;
  name: string;
  url: string;
};

export const brands: Brand[] = [
  { id: 43, slug: "diaclear", name: "Diaclear", url: "https://eshop.marosko.sk/b/DIACLEAR" },
  { id: 44, slug: "arbortech", name: "Arbortech", url: "https://eshop.marosko.sk/b/Arbortech" },
  { id: 47, slug: "scraper", name: "Scraper", url: "https://eshop.marosko.sk/b/SCRAPER" },
  { id: 49, slug: "ideaImport", name: "Idea Import.ante s.r.o.", url: "https://eshop.marosko.sk/b/Idea+Import.ante+s.r.o." },
  { id: 50, slug: "artu", name: "Artu", url: "https://eshop.marosko.sk/b/ARTU" },
  { id: 52, slug: "allround", name: "Allround", url: "https://eshop.marosko.sk/b/ALLROUND" },
  { id: 53, slug: "saburrtoothUsa", name: "Saburrtooth USA", url: "https://eshop.marosko.sk/b/Saburrtooth+USA" },
  { id: 54, slug: "akkaTools", name: "AKKA Tools", url: "https://eshop.marosko.sk/b/AKKA+Tools" },
  { id: 55, slug: "kingArthurUsa", name: "King Arthur, USA", url: "https://eshop.marosko.sk/b/King+Arthur%2CUSA" },
  { id: 56, slug: "silverline", name: "Silverline", url: "https://eshop.marosko.sk/b/Silverline" },
  { id: 57, slug: "tarpolProfesional", name: "Tarpol Profesional", url: "https://eshop.marosko.sk/b/TARPOL+Profesional" },
  { id: 58, slug: "tarpol", name: "Tarpol", url: "https://eshop.marosko.sk/b/TARPOL" },
  { id: 59, slug: "magg", name: "Magg", url: "https://eshop.marosko.sk/b/MAGG" },
  { id: 60, slug: "extolPremium", name: "Extol Premium", url: "https://eshop.marosko.sk/b/Extol+Premium" },
  { id: 61, slug: "oTools", name: "o.tools", url: "https://eshop.marosko.sk/b/o.tools" },
  { id: 63, slug: "sait", name: "Sait", url: "https://eshop.marosko.sk/b/SAIT" },
  { id: 65, slug: "triton", name: "Triton", url: "https://eshop.marosko.sk/b/Triton" },
  { id: 66, slug: "dolmar", name: "Dolmar", url: "https://eshop.marosko.sk/b/Dolmar" },
  { id: 67, slug: "andrejIrsa", name: "Andrej Irša - a-studio", url: "https://eshop.marosko.sk/b/Andrej+Ir%C5%A1a+-+a+-+studio" },
  { id: 68, slug: "oregon", name: "Oregon", url: "https://eshop.marosko.sk/b/OREGON" },
  { id: 69, slug: "manpa", name: "Manpa", url: "https://eshop.marosko.sk/b/MANPA" },
  { id: 71, slug: "tuson", name: "Tuson", url: "https://eshop.marosko.sk/b/TUSON" },
  { id: 73, slug: "wadart", name: "Wadart s.r.o", url: "https://eshop.marosko.sk/b/WADART+s.r.o" },
  { id: 74, slug: "kirjes", name: "Kirjes", url: "https://eshop.marosko.sk/b/Kirjes" },
  { id: 75, slug: "proxxon", name: "Proxxon", url: "https://eshop.marosko.sk/b/PROXXON" },
  { id: 76, slug: "lukas", name: "Lukas", url: "https://eshop.marosko.sk/b/Lukas" },
  { id: 77, slug: "nevada", name: "Nevada", url: "https://eshop.marosko.sk/b/NEVADA" },
  { id: 78, slug: "makita", name: "Makita", url: "https://eshop.marosko.sk/b/Makita" },
  { id: 80, slug: "pferdTools", name: "Pferd Tools", url: "https://eshop.marosko.sk/b/PFERD+TOOLS" },
  { id: 81, slug: "diplomat", name: "Diplomat s.r.o.", url: "https://eshop.marosko.sk/b/Diplomat+s.r.o." },
  { id: 82, slug: "ctsItalia", name: "C.T.S. Italia", url: "https://eshop.marosko.sk/b/C.T.S.++Italia" },
  { id: 83, slug: "ceraNovecento", name: "Cera Novecento", url: "https://eshop.marosko.sk/b/Cera+Novecento" },
  { id: 85, slug: "deltaplus", name: "Deltaplus", url: "https://eshop.marosko.sk/b/DELTAPLUS" },
  { id: 86, slug: "lejaTools", name: "Leja Tools", url: "https://eshop.marosko.sk/b/LEJA+tools" },
  { id: 87, slug: "madeInEu", name: "Made in EU", url: "https://eshop.marosko.sk/b/Made+in+EU" },
  { id: 88, slug: "m3", name: "3M", url: "https://eshop.marosko.sk/b/3M" },
  { id: 89, slug: "mstein", name: "M-stein s.r.o", url: "https://eshop.marosko.sk/b/M-stein+s.r.o" },
  { id: 90, slug: "holzmann", name: "Holzmann", url: "https://eshop.marosko.sk/b/Holzmann" },
  { id: 91, slug: "totalToolsCo", name: "Total Tools Co.", url: "https://eshop.marosko.sk/b/TOTAL+Tools+Co." },
  { id: 93, slug: "hermes", name: "Hermes", url: "https://eshop.marosko.sk/b/Hermes" },
  { id: 94, slug: "imperial", name: "Imperial", url: "https://eshop.marosko.sk/b/Imperial" },
  { id: 95, slug: "prano", name: "Prano", url: "https://eshop.marosko.sk/b/Prano" },
  { id: 96, slug: "bibielle", name: "Bibielle", url: "https://eshop.marosko.sk/b/bibielle" },
  { id: 97, slug: "extolCraft", name: "Extol Craft", url: "https://eshop.marosko.sk/b/Extol+Craft" },
  { id: 98, slug: "m3ScotchBrite", name: "3M-Scotch-Brite™", url: "https://eshop.marosko.sk/b/3M-Scotch-Brite%E2%84%A2" },
  { id: 99, slug: "finixa", name: "Finixa", url: "https://eshop.marosko.sk/b/Finixa" },
  { id: 100, slug: "veropal", name: "Veropal", url: "https://eshop.marosko.sk/b/Veropal" },
  { id: 101, slug: "synpo", name: "Synpo", url: "https://eshop.marosko.sk/b/Synpo" },
  { id: 102, slug: "kwiktool", name: "Kwiktool", url: "https://eshop.marosko.sk/b/Kwiktool" },
  { id: 103, slug: "scruffs", name: "Scruffs", url: "https://eshop.marosko.sk/b/Scruffs" },
  { id: 104, slug: "geko", name: "Geko", url: "https://eshop.marosko.sk/b/Geko" },
  { id: 105, slug: "wolfcraft", name: "wolfcraft", url: "https://eshop.marosko.sk/b/wolfcraft" },
  { id: 106, slug: "rockler", name: "Rockler", url: "https://eshop.marosko.sk/b/Rockler" },
  { id: 107, slug: "samsonKamnik", name: "Samson Kamnik d.o.o.", url: "https://eshop.marosko.sk/b/Samson+Kamnik+d.o.o." },
  { id: 108, slug: "prillinger", name: "Prillinger", url: "https://eshop.marosko.sk/b/PRILLINGER" },
  { id: 109, slug: "kutzall", name: "Kutzall", url: "https://eshop.marosko.sk/b/KUTZALL" },
  { id: 110, slug: "ekamant", name: "Ekamant", url: "https://eshop.marosko.sk/b/Ekamant" },
  { id: 111, slug: "noris", name: "Noris", url: "https://eshop.marosko.sk/b/NORIS" },
  { id: 112, slug: "stubai", name: "Stubai", url: "https://eshop.marosko.sk/b/STUBAI" },
  { id: 113, slug: "farTools", name: "Far Tools", url: "https://eshop.marosko.sk/b/FAR+TOOLS" },
  { id: 114, slug: "charbonnel", name: "Charbonnel", url: "https://eshop.marosko.sk/b/Charbonnel" },
  { id: 115, slug: "thlProtect", name: "THLProtect", url: "https://eshop.marosko.sk/b/THLProtect" },
  { id: 117, slug: "pr05", name: "PR05", url: "https://eshop.marosko.sk/b/PR05" },
  { id: 118, slug: "distar", name: "Distar", url: "https://eshop.marosko.sk/b/Distar" },
  { id: 119, slug: "fortum", name: "Fortum", url: "https://eshop.marosko.sk/b/fortum" },
  { id: 120, slug: "strongbold", name: "Strongbold", url: "https://eshop.marosko.sk/b/Strongbold" },
];
