export type Brand = {
  id: number;
  slug: string;
  name: string;
};

export const brands: Brand[] = [
  { id: 43, slug: "diaclear", name: "Diaclear" },
  { id: 44, slug: "arbortech", name: "Arbortech" },
  { id: 47, slug: "scraper", name: "Scraper" },
  { id: 49, slug: "ideaImport", name: "Idea Import.ante s.r.o." },
  { id: 50, slug: "artu", name: "Artu" },
  { id: 52, slug: "allround", name: "Allround" },
  { id: 53, slug: "saburrtoothUsa", name: "Saburrtooth USA" },
  { id: 54, slug: "akkaTools", name: "AKKA Tools" },
  { id: 55, slug: "kingArthurUsa", name: "King Arthur, USA" },
  { id: 56, slug: "silverline", name: "Silverline" },
  { id: 57, slug: "tarpolProfesional", name: "Tarpol Profesional" },
  { id: 58, slug: "tarpol", name: "Tarpol" },
  { id: 59, slug: "magg", name: "Magg" },
  { id: 60, slug: "extolPremium", name: "Extol Premium" },
  { id: 61, slug: "oTools", name: "o.tools" },
  { id: 63, slug: "sait", name: "Sait" },
  { id: 65, slug: "triton", name: "Triton" },
  { id: 66, slug: "dolmar", name: "Dolmar" },
  { id: 67, slug: "andrejIrsa", name: "Andrej Irša - a-studio" },
  { id: 68, slug: "oregon", name: "Oregon" },
  { id: 69, slug: "manpa", name: "Manpa" },
  { id: 71, slug: "tuson", name: "Tuson" },
  { id: 73, slug: "wadart", name: "Wadart s.r.o" },
  { id: 74, slug: "kirjes", name: "Kirjes" },
  { id: 75, slug: "proxxon", name: "Proxxon" },
  { id: 76, slug: "lukas", name: "Lukas" },
  { id: 77, slug: "nevada", name: "Nevada" },
  { id: 78, slug: "makita", name: "Makita" },
  { id: 80, slug: "pferdTools", name: "Pferd Tools" },
  { id: 81, slug: "diplomat", name: "Diplomat s.r.o." },
  { id: 82, slug: "ctsItalia", name: "C.T.S. Italia" },
  { id: 83, slug: "ceraNovecento", name: "Cera Novecento" },
  { id: 85, slug: "deltaplus", name: "Deltaplus" },
  { id: 86, slug: "lejaTools", name: "Leja Tools" },
  { id: 87, slug: "madeInEu", name: "Made in EU" },
  { id: 88, slug: "m3", name: "3M" },
  { id: 89, slug: "mstein", name: "M-stein s.r.o" },
  { id: 90, slug: "holzmann", name: "Holzmann" },
  { id: 91, slug: "totalToolsCo", name: "Total Tools Co." },
  { id: 93, slug: "hermes", name: "Hermes" },
  { id: 94, slug: "imperial", name: "Imperial" },
  { id: 95, slug: "prano", name: "Prano" },
  { id: 96, slug: "bibielle", name: "Bibielle" },
  { id: 97, slug: "extolCraft", name: "Extol Craft" },
  { id: 98, slug: "m3ScotchBrite", name: "3M-Scotch-Brite™" },
  { id: 99, slug: "finixa", name: "Finixa" },
  { id: 100, slug: "veropal", name: "Veropal" },
  { id: 101, slug: "synpo", name: "Synpo" },
  { id: 102, slug: "kwiktool", name: "Kwiktool" },
  { id: 103, slug: "scruffs", name: "Scruffs" },
  { id: 104, slug: "geko", name: "Geko" },
  { id: 105, slug: "wolfcraft", name: "wolfcraft" },
  { id: 106, slug: "rockler", name: "Rockler" },
  { id: 107, slug: "samsonKamnik", name: "Samson Kamnik d.o.o." },
  { id: 108, slug: "prillinger", name: "Prillinger" },
  { id: 109, slug: "kutzall", name: "Kutzall" },
  { id: 110, slug: "ekamant", name: "Ekamant" },
  { id: 111, slug: "noris", name: "Noris" },
  { id: 112, slug: "stubai", name: "Stubai" },
  { id: 113, slug: "farTools", name: "Far Tools" },
  { id: 114, slug: "charbonnel", name: "Charbonnel" },
  { id: 115, slug: "thlProtect", name: "THLProtect" },
  { id: 117, slug: "pr05", name: "PR05" },
  { id: 118, slug: "distar", name: "Distar" },
  { id: 119, slug: "fortum", name: "Fortum" },
  { id: 120, slug: "strongbold", name: "Strongbold" },
];
